# Generated by Django 4.0.10 on 2024-03-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='realted_post_id',
            new_name='related_post_id',
        ),
    ]
