# Generated by Django 4.0.10 on 2024-03-06 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_liked_users_alter_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked_users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
