# Generated by Django 4.0.10 on 2024-03-08 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0010_comment_liked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='related_post_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
    ]
