# Generated by Django 4.0.10 on 2024-03-08 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_comment_related_post_id_comment_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.AddField(
            model_name='comment',
            name='related_post_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='related_post', to='core.post'),
            preserve_default=False,
        ),
    ]
