# Generated by Django 4.0.10 on 2024-03-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_comment_content_type_comment_related_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='related_post_id',
            new_name='related_post',
        ),
    ]
